name: "Continuous Build (Terraform)"

on:
  push:
    paths:
      - '**/*.tf'
      - '.github/workflows/ci-terraform.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/ci-terraform.yml'
    branches:
      - main
  schedule:
    - cron: '*/40 * * * 1-5'

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
